### PR TITLE
fix: sentry whitelisted monitoring-tunnel in middlewares

### PR DESCRIPTION
**Pull request by bearpong**
- Updated sentry code to bypass ad blockers
- report console.error as sentry error. this is useful as we are currently ignoring a lot of errors by just catching them.

### CODE REVIEW

**Comment by BrownBrownBear** [comment]
@garrettparris @ninibear030 are we sure we want to log `console.error` errors in sentry? I can find this getting spammy and also if third party packages are using console.error, our sentry will pick it up

**Comment by bearpong** [comment]
@BrownBrownBear i see your point but i think we should catch errors somehow or we'll have hard times debugging errors.
However, catching console.error turned out to be useless since we're stripping all console messages off on production build, so i'm reverting this change.

I suggest we should at least stop catching errors inside swr hooks since they're already catched by swr itself. Here's an example of how we should refactore the code. Doing that we'll be able to use swr global catcher (see [packages/berajs/src/contexts/berajsProvider/context.tsx](https://github.com/berachain/monobera/pull/51/files#diff-e29bcc601d30fc8f7ab2311a630aa8f0d65b4c3cfa6bd4a0050bf398265b5566))

Screenshot 2024-09-16 at 11 04 51

**Comment by BrownBrownBear** [comment]
@bearpong we can go ahead with this method but I think being able to put a try catch around swr code allowed us to provide a variable through our call in case it failed. However, the better solution would be typing errors we receive and making sure our components don't break in production if a backend service goes offline

**Comment by bearpong** [comment]
Yeah, but this is useless if we return undefined, which would be returned anyway. I personally think it'd be better to tell users a backend service is offline rather than showing potentially wrong data.

**Review by ninibear030 — APPROVED** [review]

**Review by BrownBrownBear — APPROVED** [review]
LGTM

**Pull request merged**
