### PR TITLE
Decentralize Berps

### PR DESCRIPTION
**Pull request by bearpong**
This is still in progress. This includes:

- add fleek.config.kson
- add `generateStaticParams` to know paths at static build time
- remove searchParams on server components. This was used on `<ReferralModal>` which was a client component so it now uses `useSearchParams`.

Reached out fleek team to fix a bug regarding paths with square brackets, which would throw `401 Unauthroized` on their alias server.

Berps deployment on [https://berps-bartio.on-fleek.app/](https://berps-bartio.on-fleek.app/)

### CODE REVIEW

**Comment by BrownBrownBear** [comment]
Fix markets infinite scroll cards and markets table (in the future) to redirect to proper markets page.

**Comment by bearpong** [comment]
Everything should be okay now except for a weird extraspacing on the tradingview chart. 

It only appears once deployed on ipfs, not if you serve the static build on localhost, but it's actually inside the tv iframe.

I think this should be added on the backlog as it needs further investigation.

Screenshot 2024-08-30 at 13 42 31

**Comment by BrownBrownBear** [comment]
Before this gets merged, we need to fix the referrals URL generation in the referrals tab. It currently always points to the vercel bartio link and provides no market details in the URL. For now we can try to grab the URL from the current URL being used in browser and then also just default to ETH/USD

**Review by BrownBrownBear — CHANGES_REQUESTED** [review]
Please add referrals dynamic link generation logic with preset ETH/USD link

**Comment by BrownBrownBear** [comment]
> Everything should be okay now except for a weird extraspacing on the tradingview chart.
> 
> It only appears once deployed on ipfs, not if you serve the static build on localhost, but it's actually inside the tv iframe.
> 
> I think this should be added on the backlog as it needs further investigation.
> 
> Screenshot 2024-08-30 at 13 42 31

Can you create a ticket for this on JIRA so that we have it recorded? Not a big deal because people won't use it right now but this should be investigated later. Might have something to do with how things are being loaded or css that's included in the iframe.

**Comment by bearpong** [comment]
everything should be fixed now. 

TV bug was reported on JIRA as BFE-192

**Review by BrownBrownBear — APPROVED** [review]
LGTM other than the TV toolbars not working in fleek. The IPFS links work and the vercel links work so it might be the way TV is imported in fleek?

**Pull request merged**
